name: Build FFmpeg Android

on:
  workflow_dispatch:

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest
    name: Build FFmpeg .so and headers for Android

    env:
      ANDROID_NDK_VERSION: r26d
      FFMPEG_VERSION: 6.1.1
      DECODE_LIST: "h264,mpeg4"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yasm make pkg-config curl unzip git

      - name: Download Android NDK
        run: |
          curl -L https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip -o ndk.zip
          unzip ndk.zip
          mv android-ndk-${ANDROID_NDK_VERSION} $HOME/android-ndk

      - name: Download FFmpeg source
        run: |
          curl -L https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 -o ffmpeg.tar.bz2
          tar -xjf ffmpeg.tar.bz2
          mv ffmpeg-${FFMPEG_VERSION} ffmpeg

      - name: Build FFmpeg for Android
        run: |
          set -eux

          FFMPEG_PATH="$GITHUB_WORKSPACE/ffmpeg"
          NDK_PATH="$HOME/android-ndk"
          HOST_PLATFORM=linux-x86_64
          ENABLED_DECODERS=(${DECODE_LIST//,/ })

          cd "$FFMPEG_PATH"
          mkdir -p android-output

          build_arch() {
            ABI=$1
            ARCH=$2
            CPU=$3
            CROSS_PREFIX=$4
            EXTRA_CFLAGS=$5
            EXTRA_LDFLAGS=$6
            DISABLE_ASM=$7
            API_LEVEL=$8

            OUTPUT_DIR=$FFMPEG_PATH/android-output/$ABI
            mkdir -p $OUTPUT_DIR

            COMMON_OPTIONS="
              --target-os=android
              --enable-static
              --disable-shared
              --disable-doc
              --disable-programs
              --disable-everything
              --disable-avdevice
              --disable-avformat
              --disable-swscale
              --disable-postproc
              --disable-avfilter
              --disable-symver
              --enable-swresample
              --extra-ldexeflags=-pie
              --disable-v4l2-m2m
              --disable-vulkan
              $DISABLE_ASM
            "

            for decoder in "${ENABLED_DECODERS[@]}"; do
              COMMON_OPTIONS+=" --enable-decoder=${decoder}"
            done

            TOOLCHAIN="$NDK_PATH/toolchains/llvm/prebuilt/${HOST_PLATFORM}/bin"
            export PATH=$TOOLCHAIN:$PATH

            ./configure \
              --prefix=$OUTPUT_DIR \
              --libdir=$OUTPUT_DIR/lib \
              --incdir=$OUTPUT_DIR/include \
              --arch=$ARCH \
              --cpu=$CPU \
              --cross-prefix="$TOOLCHAIN/$CROSS_PREFIX" \
              --nm="$TOOLCHAIN/llvm-nm" \
              --ar="$TOOLCHAIN/llvm-ar" \
              --ranlib="$TOOLCHAIN/llvm-ranlib" \
              --strip="$TOOLCHAIN/llvm-strip" \
              --cc="$TOOLCHAIN/${CROSS_PREFIX}clang" \
              --cxx="$TOOLCHAIN/${CROSS_PREFIX}clang++" \
              --extra-cflags="$EXTRA_CFLAGS -fPIC -D__ANDROID_API__=$API_LEVEL" \
              --extra-ldflags="$EXTRA_LDFLAGS" \
              $COMMON_OPTIONS

            make -j$(nproc)
            make install-libs
            make install
            make clean
          }

          build_arch "armeabi-v7a" "arm" "armv7-a" "armv7a-linux-androideabi21-" \
            "-march=armv7-a -mfloat-abi=softfp" "-Wl,--fix-cortex-a8" "" 21

          build_arch "arm64-v8a" "aarch64" "armv8-a" "aarch64-linux-android21-" \
            "" "" "" 21

          build_arch "x86" "x86" "i686" "i686-linux-android21-" \
            "" "" "--disable-asm" 21

          build_arch "x86_64" "x86_64" "x86-64" "x86_64-linux-android21-" \
            "" "" "--disable-asm" 21

      - name: Upload All FFmpeg Outputs (libs + headers)
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-android-full
          path: ffmpeg/android-output/
