name: Build FFmpeg Android

on:
  workflow_dispatch:

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest
    name: Build FFmpeg .so for Android

    env:
      ANDROID_NDK_VERSION: r26d
      FFMPEG_VERSION: 6.1.1
      DECODE_LIST: "h264,mpeg4"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yasm make pkg-config curl unzip git

      - name: Download Android NDK
        run: |
          curl -L https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip -o ndk.zip
          unzip ndk.zip
          mv android-ndk-${ANDROID_NDK_VERSION} $HOME/android-ndk

      - name: Download FFmpeg source
        run: |
          curl -L https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 -o ffmpeg.tar.bz2
          tar -xjf ffmpeg.tar.bz2
          mv ffmpeg-${FFMPEG_VERSION} ffmpeg

      - name: Build FFmpeg for Android
        run: |
          set -eux

          FFMPEG_MODULE_PATH="$GITHUB_WORKSPACE/ffmpeg"
          NDK_PATH="$HOME/android-ndk"
          HOST_PLATFORM=linux-x86_64
          ENABLED_DECODERS=(${DECODE_LIST//,/ })

          cd $FFMPEG_MODULE_PATH
          mkdir -p android-libs

          build_arch() {
            ABI=$1
            ARCH=$2
            CPU=$3
            CROSS_PREFIX=$4
            LIBDIR=$5
            EXTRA_CFLAGS=$6
            EXTRA_LDFLAGS=$7
            DISABLE_ASM=$8
            API_LEVEL=$9

            COMMON_OPTIONS="
              --target-os=android
              --enable-static
              --disable-shared
              --disable-doc
              --disable-programs
              --disable-everything
              --disable-avdevice
              --disable-avformat
              --disable-swscale
              --disable-postproc
              --disable-avfilter
              --disable-symver
              --enable-swresample
              --extra-ldexeflags=-pie
              --disable-v4l2-m2m
              --disable-vulkan
              ${DISABLE_ASM}
            "

            for decoder in "${ENABLED_DECODERS[@]}"; do
              COMMON_OPTIONS="${COMMON_OPTIONS} --enable-decoder=${decoder}"
            done

            TOOLCHAIN="$NDK_PATH/toolchains/llvm/prebuilt/${HOST_PLATFORM}/bin"
            export PATH=$TOOLCHAIN:$PATH

            ./configure \
              --libdir=${LIBDIR} \
              --prefix=${LIBDIR} \
              --arch=${ARCH} \
              --cpu=${CPU} \
              --cross-prefix="${TOOLCHAIN}/${CROSS_PREFIX}" \
              --nm="${TOOLCHAIN}/llvm-nm" \
              --ar="${TOOLCHAIN}/llvm-ar" \
              --ranlib="${TOOLCHAIN}/llvm-ranlib" \
              --strip="${TOOLCHAIN}/llvm-strip" \
              --cc="${TOOLCHAIN}/${CROSS_PREFIX}clang" \
              --cxx="${TOOLCHAIN}/${CROSS_PREFIX}clang++" \
              --extra-cflags="${EXTRA_CFLAGS} -fPIC -D__ANDROID_API__=${API_LEVEL}" \
              --extra-ldflags="${EXTRA_LDFLAGS}" \
              ${COMMON_OPTIONS}

            make -j$(nproc)
            make install-libs
            make clean
          }

          # ARMv7
          build_arch "armeabi-v7a" "arm" "armv7-a" "armv7a-linux-androideabi21-" "android-libs/armeabi-v7a" \
            "-march=armv7-a -mfloat-abi=softfp" "-Wl,--fix-cortex-a8" "" 21

          # ARM64
          build_arch "arm64-v8a" "aarch64" "armv8-a" "aarch64-linux-android21-" "android-libs/arm64-v8a" \
            "" "" "" 21

          # x86
          build_arch "x86" "x86" "i686" "i686-linux-android21-" "android-libs/x86" \
            "" "" "--disable-asm" 21

          # x86_64
          build_arch "x86_64" "x86_64" "x86-64" "x86_64-linux-android21-" "android-libs/x86_64" \
            "" "" "--disable-asm" 21

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-android-libs
          path: ffmpeg/android-libs/
