name: Build FFmpeg for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FFMPEG_VERSION: "6.0"
  NDK_VERSION: "r25c"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up NDK
      run: |
        mkdir -p ndk
        curl -L https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip -o ndk.zip
        unzip -q ndk.zip -d ndk
        mv ndk/android-ndk-${{ env.NDK_VERSION }} ndk
        echo "NDK_PATH=$(pwd)/ndk" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config bzip2

    - name: Download and extract FFmpeg
      run: |
        curl -L https://ffmpeg.org/releases/ffmpeg-${{ env.FFMPEG_VERSION }}.tar.bz2 -o ffmpeg.tar.bz2
        tar -xjf ffmpeg.tar.bz2
        mv ffmpeg-${{ env.FFMPEG_VERSION }} ffmpeg
        rm ffmpeg.tar.bz2

    - name: Build for all ABIs
      run: |
        cd ffmpeg
        
        # Common configuration flags
        COMMON_FLAGS="
          --enable-static
          --disable-shared
          --disable-programs
          --disable-doc
          --disable-avdevice
          --disable-postproc
          --disable-avfilter
          --disable-symver
          --disable-v4l2-m2m
          --disable-vulkan
          --enable-avformat
          --enable-swresample
          --enable-swscale
          --enable-decoder=aac,mp3,h264,hevc,vp8,vp9,flac,opus,vorbis
        "

        build_abi() {
          local abi=$1
          local arch=$2
          local cpu=$3
          local prefix=$4
          local cflags=$5
          local ldflags=$6
          local extra_flags=$7

          ./configure \
            --prefix=./output/$abi \
            --target-os=android \
            --arch=$arch \
            --cpu=$cpu \
            --cross-prefix="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/$prefix" \
            --nm="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm" \
            --ar="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
            --ranlib="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib" \
            --strip="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip" \
            --extra-cflags="$cflags" \
            --extra-ldflags="$ldflags" \
            $COMMON_FLAGS $extra_flags

          make -j$(nproc)
          make install
          make clean
        }

        # Build each ABI
        build_abi "armeabi-v7a" "arm" "armv7-a" "armv7a-linux-androideabi21-clang" \
          "-march=armv7-a -mfloat-abi=softfp" "-Wl,--fix-cortex-a8" ""

        build_abi "arm64-v8a" "aarch64" "armv8-a" "aarch64-linux-android21-clang" \
          "" "" ""

        build_abi "x86" "x86" "i686" "i686-linux-android21-clang" \
          "" "" "--disable-asm"

        build_abi "x86_64" "x86_64" "x86-64" "x86_64-linux-android21-clang" \
          "" "" "--disable-asm"

    - name: Package artifacts
      run: |
        cd ffmpeg/output
        tar -czvf ../../ffmpeg-android-libs.tar.gz *
        mkdir -p ../../artifacts
        mv ../../ffmpeg-android-libs.tar.gz ../../artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-android-libs
        path: artifacts/ffmpeg-android-libs.tar.gz
