name: Build FFmpeg for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up NDK
      run: |
        mkdir -p ndk
        curl -L https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -o ndk.zip
        unzip -q ndk.zip -d ndk
        mv ndk/*/* ndk/
        echo "NDK_PATH=$(pwd)/ndk" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config

    - name: Prepare FFmpeg
      run: |
        # Clone FFmpeg if not present in repo
        if [ ! -d "ffmpeg" ]; then
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
        fi
        cd ffmpeg

    - name: Build for all ABIs
      run: |
        cd ffmpeg
        COMMON_FLAGS="
          --enable-static
          --disable-shared
          --disable-programs
          --disable-doc
          --enable-avformat
          --enable-swresample
          --enable-swscale
          --enable-decoder=aac,mp3,h264,hevc,vp8,vp9,flac,opus,vorbis
          --disable-everything-else
        "

        build_abi() {
          ./configure \
            --prefix=./output/$1 \
            --target-os=android \
            --arch=$2 \
            --cpu=$3 \
            --cross-prefix="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/$4-" \
            --nm="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm" \
            --ar="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
            --extra-cflags="$5" \
            --extra-ldflags="$6" \
            $COMMON_FLAGS $7

          make -j$(nproc)
          make install
          make clean
        }

        # Build each ABI
        build_abi "armeabi-v7a" "arm" "armv7-a" "armv7a-linux-androideabi21" \
          "-march=armv7-a -mfloat-abi=softfp" "-Wl,--fix-cortex-a8" ""

        build_abi "arm64-v8a" "aarch64" "armv8-a" "aarch64-linux-android21" \
          "" "" ""

        build_abi "x86" "x86" "i686" "i686-linux-android21" \
          "" "" "--disable-asm"

        build_abi "x86_64" "x86_64" "x86-64" "x86_64-linux-android21" \
          "" "" "--disable-asm"

    - name: Package artifacts
      run: |
        cd ffmpeg/output
        tar -czvf ../../ffmpeg-android-libs.tar.gz *
        mkdir -p ../../artifacts
        mv ../../ffmpeg-android-libs.tar.gz ../../artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-android-libs
        path: artifacts/ffmpeg-android-libs.tar.gz
